"""
accounts/serializers.py

Serializers for User registration, profile, and JWT token handling.
"""

from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password
from rest_framework import serializers
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer

User = get_user_model()


# --------------------------------------------------------------------------- #
# JWT — enriched token payload
# --------------------------------------------------------------------------- #

class CustomTokenObtainPairSerializer(TokenObtainPairSerializer):
    """Add user role and username to the JWT payload."""

    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)
        token["username"] = user.username
        token["role"] = user.role
        token["email"] = user.email
        return token


# --------------------------------------------------------------------------- #
# User serializers
# --------------------------------------------------------------------------- #

class UserRegistrationSerializer(serializers.ModelSerializer):
    """
    Handles new user sign-up including password confirmation.

    Security note: `role` is intentionally excluded from this serializer.
    All new accounts are created as `regular` users (the model default).
    Elevation to `organizer` is performed exclusively through Django Admin
    to prevent privilege self-escalation via the API.
    """

    password = serializers.CharField(
        write_only=True,
        required=True,
        validators=[validate_password],
    )
    password2 = serializers.CharField(write_only=True, required=True)

    class Meta:
        model = User
        fields = [
            "id",
            "username",
            "email",
            "first_name",
            "last_name",
            "password",
            "password2",
        ]
        # `role` is NOT listed here — model default (regular) always applies.

    def validate(self, attrs):
        if attrs["password"] != attrs.pop("password2"):
            raise serializers.ValidationError(
                {"password": "Password fields did not match."}
            )
        return attrs

    def create(self, validated_data):
        user = User.objects.create_user(**validated_data)
        return user


class UserProfileSerializer(serializers.ModelSerializer):
    """Read / update current user's profile."""

    class Meta:
        model = User
        fields = [
            "id",
            "username",
            "email",
            "first_name",
            "last_name",
            "role",
            "avatar",
            "bio",
            "date_joined",
        ]
        read_only_fields = ["id", "username", "role", "date_joined"]


class PublicUserSerializer(serializers.ModelSerializer):
    """Minimal public view of a user (e.g. event organizer info)."""

    class Meta:
        model = User
        fields = ["id", "username", "first_name", "last_name", "avatar"]


# --------------------------------------------------------------------------- #
# Password Reset serializers
# --------------------------------------------------------------------------- #

class PasswordResetRequestSerializer(serializers.Serializer):
    """
    Validates the email for POST /api/auth/password/reset/.

    Deliberately returns a generic success message whether or not the
    email exists — this prevents user enumeration attacks (an attacker
    cannot tell whether an email address is registered by reading the
    API response).
    """

    email = serializers.EmailField(required=True)

    def validate_email(self, value):
        # Normalize to lowercase for consistent lookup
        return value.lower().strip()


class PasswordResetConfirmSerializer(serializers.Serializer):
    """
    Validates and applies a password reset for POST /api/auth/password/reset/confirm/.

    Accepts:
      - uid        : base64-encoded user primary key (generated by Django's
                     PasswordResetTokenGenerator)
      - token      : one-time reset token (expires after PASSWORD_RESET_TIMEOUT
                     seconds, default 3 days)
      - new_password  : the desired new password
      - new_password2 : confirmation — must match new_password

    Token validation uses Django's `default_token_generator` which is the
    same mechanism used by the built-in admin password reset view, so it
    is battle-tested and safe.
    """

    uid            = serializers.CharField(required=True)
    token          = serializers.CharField(required=True)
    new_password   = serializers.CharField(
        write_only=True,
        required=True,
        validators=[validate_password],
    )
    new_password2  = serializers.CharField(write_only=True, required=True)

    def validate(self, attrs):
        from django.utils.http import urlsafe_base64_decode
        from django.contrib.auth.tokens import default_token_generator

        # ── Confirm passwords match ────────────────────────────────────────
        if attrs["new_password"] != attrs["new_password2"]:
            raise serializers.ValidationError(
                {"new_password": "Password fields did not match."}
            )

        # ── Decode UID → user ──────────────────────────────────────────────
        try:
            uid_decoded = urlsafe_base64_decode(attrs["uid"]).decode("utf-8")
            user = User.objects.get(pk=uid_decoded)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            raise serializers.ValidationError(
                {"uid": "Invalid or expired password reset link."}
            )

        # ── Validate token ─────────────────────────────────────────────────
        if not default_token_generator.check_token(user, attrs["token"]):
            raise serializers.ValidationError(
                {"token": "Invalid or expired password reset token."}
            )

        # Stash the resolved user so the view doesn't have to decode again
        attrs["user"] = user
        return attrs

