# Generated by Django 6.0.5 on 2026-05-06 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('music', 'Music'), ('tech', 'Tech'), ('food', 'Food'), ('arts', 'Arts')], db_index=True, max_length=10)),
                ('date', models.DateTimeField(db_index=True)),
                ('venue_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Ticket price in USD. Set to 0.00 for free events.', max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude of the venue.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude of the venue.', max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, help_text='Poster or banner image for the event.', null=True, upload_to='events/images/')),
                ('total_tickets', models.PositiveIntegerField(default=100, help_text='Maximum number of tickets available.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished events are hidden from public listings.')),
                ('organizer', models.ForeignKey(help_text='The Event Organizer who created this event.', on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_hash', models.CharField(db_index=True, editable=False, help_text='Unique SHA-256 hash — encode this in a QR code.', max_length=64, unique=True)),
                ('is_scanned', models.BooleanField(default=False, help_text='Flipped to True when the QR code is scanned at the door.')),
                ('scanned_at', models.DateTimeField(blank=True, help_text='Timestamp when the ticket was scanned.', null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('price_paid', models.DecimalField(decimal_places=2, help_text='Price at the time of purchase (snapshot).', max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
