# Generated by Django 6.0.5 on 2026-05-08 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the like was created.')),
                ('event', models.ForeignKey(help_text='The event that was liked.', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='events.event')),
                ('user', models.ForeignKey(help_text='The user who liked this event.', on_delete=django.db.models.deletion.CASCADE, related_name='liked_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Event Like',
                'verbose_name_plural': 'User Event Likes',
                'ordering': ['-liked_at'],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
