# Generated by Django 6.0.5 on 2026-05-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_user_event_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEventLike',
        ),
    ]
